autoservice/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:masina_id>', views.automobilis, name='automobilis'),
    path('uzsakymai/', views.Uzsakymai.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>', views.Uzsakymo_info.as_view(), name='uzsakymo_info'),
    path('search/', views.search, name='search'),
    path('myorders/', views.User_uzsakymas.as_view(), name='mano_uzsakymai'),
    path('myorders/<int:pk>', views.UzsakymasByUserDetailView.as_view(), name='mano_uzsakymas'),
    path('myorders/new', views.OrderByUserCreateView.as_view(), name='mano_uzsakymas_naujas'),
    path('myorders/<int:pk>/update', views.OrderByUserUpdateView.as_view(), name='my_order_update'),
    path('myorders/<int:pk>/delete', views.OrderByUserDeleteView.as_view(), name='my_order_delete'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autoservice/', include('autoservice.urls')),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

autoservice/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from datetime import date

from tinymce.models import HTMLField


# Create your models here.

class Automobilio_modelis(models.Model):
    marke = models.CharField('Marke',max_length=100)
    modelis = models.CharField('Modelis', max_length=100)

    def __str__(self):
         return f'{self.marke} {self.modelis}'

    class Meta:
        verbose_name = 'Automobilio modelis'
        verbose_name_plural = 'Automobilio modeliai'

class Automobilis(models.Model):
    valstybinis_nr = models.CharField('Valstybinis Nr.',max_length=100,unique=True)
    automobilio_modelis = models.ForeignKey(Automobilio_modelis, on_delete=models.CASCADE)
    vin_kodas = models.CharField('VIN kodas', max_length=50)
    klientas = models.CharField('Klientas', max_length=200)
    nuotrauka = models.ImageField('Nuotrauka', upload_to='automobiliai', null=True, blank=True)
    description = HTMLField(default='Sveiki!')

    def __str__(self):
         return f'{self.valstybinis_nr}  (VIN {self.vin_kodas})   {self.automobilio_modelis}'

    class Meta:
        verbose_name = 'Automobilis'
        verbose_name_plural = 'Automobiliai'

class Busena(models.Model):
    pavadinimas = models.CharField('Būsena', max_length=100)

    def __str__(self):
        return self.pavadinimas

    class Meta:
        verbose_name = 'Būsena'
        verbose_name_plural = 'Būsenos'

class Uzsakymas(models.Model):
    data = models.CharField('Data',max_length=100)
    automobilio = models.ForeignKey(Automobilis, on_delete=models.CASCADE)
    status = models.ForeignKey(Busena, on_delete=models.DO_NOTHING, verbose_name='Būsena')
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    terminas = models.DateField('Grąžinti iki', null=True, blank=True)


    @property
    def is_overdue(self):
        if self.terminas and date.today() > self.terminas:
            return True
        return False


    def __str__(self):
         return f'{self.data} (Automobilio numeris {self.automobilio.valstybinis_nr})'

    class Meta:
        verbose_name = 'Užsakymas'
        verbose_name_plural = 'Užsakymai'

class Paslauga(models.Model):
    pavadinimas = models.CharField('Pavadinimas',max_length=500)
    kaina = models.IntegerField('Kaina')

    def __str__(self):
        return self.pavadinimas

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'

class Uzsakymo_eilute(models.Model):
    paslauga = models.ForeignKey(Paslauga, on_delete=models.CASCADE)
    uzsakymas = models.ForeignKey(Uzsakymas, on_delete=models.CASCADE )
    kiekis = models.CharField('Kiekis',max_length=100)

    def __str__(self):
        return f'Uzsakymo id ({self.uzsakymas})'

    class Meta:
        verbose_name = 'Užsakymo eilutė'
        verbose_name_plural = 'Užsakymų eilutės'


class UzsakymoAtsiliepimas(models.Model):
    uzsakymas = models.ForeignKey('Uzsakymas', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)

    class Meta:
        verbose_name = "Atsiliepimas"
        verbose_name_plural = 'Atsiliepimai'
        ordering = ['-date_created']

class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="profile_pics/default.jpg", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 150 or img.width > 150:
            output_size = (150, 150)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'Profiliai'

autoservice/forms.py
from django.contrib.auth.models import User

from .models import UzsakymoAtsiliepimas, Profilis, Uzsakymas
from django import forms

class UzsakymasReviewForm(forms.ModelForm):
    class Meta:
        model = UzsakymoAtsiliepimas
        fields = ('uzsakymas','reviewer','content')
        widgets = {'uzsakymas': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']




class DateInput(forms.DateInput):
    input_type = 'date'

class UserUzsakymasCreateForm(forms.ModelForm):
    class Meta:
        model = Uzsakymas
        fields = [ 'automobilio','reader', 'terminas']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}

autoservice/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,reverse
from django.views import generic
from django.views.generic.edit import FormMixin, CreateView, UpdateView, DeleteView
from .forms import UzsakymasReviewForm, UserUzsakymasCreateForm
from .models import Automobilio_modelis, Automobilis, Paslauga,Uzsakymo_eilute,Uzsakymas,Busena
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .forms import UzsakymasReviewForm, UserUpdateForm, ProfilisUpdateForm
# Create your views here.

def index(request):
    num_paslauga = Paslauga.objects.all().count()
    num_automobiliai = Automobilis.objects.all().count()
    num_uzsakymu = Uzsakymas.objects.filter(status__pavadinimas='Įvykdytas').count()

    # perduodame informaciją į šabloną žodyno pavidale:
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'paslaugos': num_paslauga,
        'uzsakymai': num_uzsakymu,
        'automobiliai': num_automobiliai,
        'num_visits': num_visits,
    }

    # renderiname index.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)

def automobiliai(request):
    automobiliai_list = Automobilis.objects.all().order_by('id')
    paginator = Paginator(automobiliai_list, 2)
    page_number = request.GET.get('page')
    automobiliai = paginator.get_page(page_number)
    context = {
        'automobiliai':automobiliai
    }
    return render(request,'automobiliai.html',context=context)

def automobilis(request,masina_id):
    masina = get_object_or_404(Automobilis, pk=masina_id)
    return render(request,'automobilis.html',{'automobilis':masina})


class Uzsakymai(generic.ListView):
    model = Uzsakymas
    paginate_by = 2
    template_name = "uzsakymai.html"
    context_object_name = "uzsakymu_sarasas"
    ordering = ['id']

class Uzsakymo_info(FormMixin,generic.DetailView):
    model = Uzsakymas
    template_name = 'uzsakymas.html'
    form_class = UzsakymasReviewForm

    # nurodome, kur atsidursime komentaro sėkmės atveju.
    def get_success_url(self):
        return reverse('uzsakymo_info', kwargs={'pk': self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # štai čia nurodome, kad knyga bus būtent ta, po kuria komentuojame, o vartotojas bus tas, kuris yra prisijungęs.
    def form_valid(self, form):
        form.instance.uzsakymas = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(Uzsakymo_info, self).form_valid(form)


def search(request):
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(Q(klientas__icontains=query) | Q(valstybinis_nr__icontains=query) | Q(automobilio_modelis__modelis__icontains=query) | Q(vin_kodas__icontains=query) |Q(automobilio_modelis__marke__icontains=query))
    return render(request, 'search.html', {'automobiliai': search_results, 'query': query})

class User_uzsakymas(LoginRequiredMixin,generic.ListView):
    model = Uzsakymas
    template_name = 'user_uzsakymai.html'
    context_object_name = 'uzsakymu_sarasas'
    paginate_by = 5

    def get_queryset(self):
        return Uzsakymas.objects.filter(reader=self.request.user).order_by('terminas')

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')

@login_required
def profilis(request):
    return render(request, 'profilis.html')



@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)


class UzsakymasByUserDetailView(LoginRequiredMixin, Uzsakymo_info):
    model = Uzsakymas
    template_name = 'user_uzsakymas.html'

class OrderByUserCreateView(LoginRequiredMixin, CreateView):
    model = Uzsakymas
    # fields = [ 'automobilio','terminas','status']
    success_url = "/autoservice/myorders/"
    template_name = 'user_order_form.html'
    form_class = UserUzsakymasCreateForm

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)


class OrderByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Uzsakymas
    fields = ['automobilio','terminas']
    success_url = "/autoservice/myorders/"
    template_name = 'user_order_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def test_func(self):
        Uzsakymas = self.get_object()
        return self.request.user == Uzsakymas.reader

class OrderByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Uzsakymas
    success_url = "/autoservice/myorders/"
    template_name = 'user_order_delete.html'

    def test_func(self):
        Uzsakymas = self.get_object()
        return self.request.user == Uzsakymas.reader

autoservice/templates/automobiliai.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Automobilių sąrašas -->
  <h1>Automobiliai</h1>
  <p>Šiuo metu užsiregistravę automobiliai:</p>

  <div class="row">
    {% for automobilis in automobiliai %}
      <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
          {% if automobilis.nuotrauka %}
            <img src="{{ automobilis.nuotrauka.url }}" class="card-img-top" alt="{{ automobilis.automobilio_modelis }}">
          {% else %}
            <img src="{% static 'img/no-image.png' %}" class="card-img-top" alt="Nėra nuotraukos">
          {% endif %}
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">{{ automobilis.gamintojas }}</h6>
            <p class="card-text">
              <a href="{% url 'automobilis' automobilis.id %}">{{ automobilis.automobilio_modelis }}</a>
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- Paginacija -->
  <div class="container puslapiai">
    <nav aria-label="Puslapiavimo navigacija">
      {% if automobiliai.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
          {% for i in automobiliai.paginator.page_range %}
            {% if automobiliai.number == i %}
              <li class="page-item active" aria-current="page">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
    </nav>
  </div>
{% endblock %}

autoservice/templates/automobilis.html
{% extends "base.html" %}

{% block content %}
    <div class="container automobilis">
    <h4>Detali informacija:</h4>
        <img src="{{ automobilis.nuotrauka.url }}" style="margin-bottom: 20px;">
    <ul>
        <li>Savininkas:  {{automobilis.klientas}}</li>
        <li>Automobilio modelis:  {{automobilis.automobilio_modelis}}</li>
        <li>Valstybinis numeris:  {{ automobilis.valstybinis_nr }}</li>
        <li>VIN kodas:  {{automobilis.vin_kodas}}</li>
        <li>{{ automobilis.description | safe }}</li>
    </ul>
    </div>
{% endblock %}

autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Autoservisas</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Autoservisas</a>
      <ul class="navbar-nav mx-2">
                  {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mano_uzsakymai' %}">Mano užsakymai</a></li>
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
<!--                <button type="submit">Atsijungti</button>-->
                  <button type="submit" class="btn btn-outline-danger">Atsijungti</button>
              </form>
            </li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}">Prisijungti</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
          {% endif %}
        <li class="nav-item"><a class="nav-link" href="{% url 'mano_uzsakymas_naujas'%}?next=/autoservice">Naujas</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Pradžia</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'automobiliai' %}">Visi automobiliai</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'uzsakymai' %}">Visi užsakymai</a></li>

      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
        <input class="form-control me-2" name="query" type="text" placeholder="Paieška">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>

  </nav>
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                {{ message }}
        </div>
    {% endfor %}
    {% endif %}
  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

autoservice/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Autoservisas</h1>
  <ul>
    <li><strong>Šiuo metu teikiame: </strong>{{ paslaugos }} paslaugas </li>
    <li><strong>Iš viso esame atlikę: </strong> {{ uzsakymai }} užsakymus </li>
    <li><strong>Šiuo metu aptarnaujamų automobilių skaičius: </strong> {{ automobiliai }}  </li>
  </ul>
  <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

autoservice/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

autoservice/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login' %}"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

autoservice/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{ query }}" rezultatai:</h1>
  <br/>

  <!-- Paieškos forma -->
  <form method="get" action="{% url 'search' %}">
    <input type="text" name="query" placeholder="Ieškoti pagal savininką, modelį, valstybinį numerį ar VIN kodą" value="{{ query }}">
    <button type="submit">Ieškoti</button>
  </form>

  <br/>

  {% if automobiliai %}
    <ul>
      {% for automobilis in automobiliai %}
        <li>
          <a href="{% url 'automobilis' automobilis.id %}">
            {{ automobilis.valstybinis_nr }} -
            {{ automobilis.automobilio_modelis }} |
            Klientas: {{ automobilis.klientas }} |
            VIN: {{ automobilis.vin_kodas }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

{% endblock %}

autoservice/templates/user_order_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti užsakymą</legend>
            <h2>Ar tikrai norite ištrinti užsakymą {{ object.id }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'mano_uzsakymas' object.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

autoservice/templates/uzsakymas.html
{% extends "base.html" %}

{% block content %}
  <div class="container uzsakymas">
    <h4>Detali užsakymo informacija:</h4>
    <img class="rounded-circle" src="{{uzsakymas.reader.profilis.nuotrauka.url}}">
    <ul>
      <li><strong>ID:</strong> {{ uzsakymas.id }}</li>
      <li><strong>Data:</strong> {{ uzsakymas.data }}</li>
      <li><strong>Būsena:</strong> {{ uzsakymas.status }}</li>
    </ul>

    <div style="margin-left: 20px; margin-top: 20px;">
      <h4>Užsakymo eilutės:</h4>
      {% if uzsakymas.uzsakymo_eilute_set.exists %}
        {% for eilute in uzsakymas.uzsakymo_eilute_set.all %}
          <hr>
          <p><strong>Paslauga:</strong> {{ eilute.paslauga.pavadinimas }}</p>
          <p><strong>Kaina (už vienetą):</strong> {{ eilute.paslauga.kaina }} EUR</p>
          <p><strong>Kiekis:</strong> {{ eilute.kiekis }}</p>
        {% endfor %}
      {% else %}
        <p class="text-warning">Šis užsakymas neturi paslaugų.</p>
      {% endif %}
    </div>
  </div>

  <div style="margin-top: 20px;">
    <h4>Atsiliepimai:</h4>
    {% if uzsakymas.uzsakymoatsiliepimas_set.exists %}
      {% for review in uzsakymas.uzsakymoatsiliepimas_set.all %}
        <hr>

        <p><strong>Klientas:</strong> {{ review.reviewer }} <strong>Data:</strong> {{ review.date_created}}</p>
      <img class="rounded-circle" src="{{review.reviewer.profilis.nuotrauka.url}}">
        <p>{{ review.content }}</p>
      {% endfor %}
    {% else %}
      <p class="text-warning">Užsakymas neturi atsiliepimų.</p>
    {% endif %}
      {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.content }}</br>
      <input type="submit" value="Išsaugoti">
    </form>
  </div>
  {% endif %}
  </div>
{% endblock %}
}